//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Department
    {
        public Department()
        {
            this.Users = new HashSet<User>();
        }
    
        public int DeptId { get; set; }

        [Required(ErrorMessage = "Please select your department name")]
        [Display(Name = "Department Name")]
        public string DeptName { get; set; }

        public virtual ICollection<User> Users { get; set; }
    }
}
