//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.Models
{
    public partial class User
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public int DeptId { get; set; }
        public string City { get; set; }
        public string Gender { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
